# Generated by Django 5.2.3 on 2025-07-24 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("usermonth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tot_cal_kcal", models.IntegerField(default=0)),
                ("tot_protein_g", models.FloatField(default=0.0)),
                ("tot_fat_g", models.FloatField(default=0.0)),
                ("tot_carbs_g", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meal_score_avg", models.FloatField(default=0.0)),
                ("ai_insights", models.TextField(blank=True, null=True)),
                ("journal_entry", models.TextField(blank=True, null=True)),
                ("vibe_score", models.IntegerField(default=0)),
                (
                    "custom_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="usermonth.usermonth",
                    ),
                ),
            ],
        ),
    ]
