# Generated by Django 5.2.3 on 2025-07-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("foodPhoto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("protein_g", models.FloatField(blank=True, null=True)),
                ("carbs_g", models.FloatField(blank=True, null=True)),
                ("fat_g", models.FloatField(blank=True, null=True)),
                ("cal_kcal", models.IntegerField(blank=True, null=True)),
                ("nutrients", models.JSONField(blank=True, null=True)),
                (
                    "food_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="foodPhoto.photo",
                    ),
                ),
            ],
        ),
    ]
