# Generated by Django 5.2.3 on 2025-07-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usergoal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoal",
            name="carbs_perc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="daily_cal_kcal",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="daily_carbs_g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="daily_fat_g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="daily_protein_g",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="fat_perc",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usergoal",
            name="protein_perc",
            field=models.FloatField(default=0.0),
        ),
    ]
